"""The CRF encoder's graph must not drift from what the shipped weights mean.

Every barcode CRF checkpoint in escapepod-models was trained through this
architecture. A changed layer, a flipped LSTM direction, or a blank spliced in
at the wrong end of each state group all load cleanly, produce the right
shapes, and are silently wrong — so the graph is pinned against a committed
reference (``fixtures/crf_encoder_reference.npz``, regenerated by
``fixtures/gen_crf_encoder_reference.py``).

**What this test is and is not.** It pins the architecture against *itself over
time*, using seeded weights, which is the part that can live in this repo: leech
ships no model binaries. The stronger claim — that the encoder reproduces the
*shipped* checkpoints bit-for-bit — needs those checkpoints, so it stays in
escapepod-models where they live, against each export's ``reference_io.npz``.

The comparison here carries a tolerance rather than asserting bit-equality,
because the fixture crosses machines and torch releases and CPU LSTM kernels do
not promise bit-reproducibility across either. It is still tight against what it
guards: every architecture error listed above moves scores by whole units on a
[-5, 5] scale, five orders of magnitude above the tolerance.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pytest
import torch

from leech.crf import CrfEncoder, EncoderConfig, load_crf_state_dict

FIXTURE = Path(__file__).parent / "fixtures" / "crf_encoder_reference.npz"


def test_matches_the_committed_reference():
    from fixtures.gen_crf_encoder_reference import CONFIG, seeded_weights

    ref = np.load(FIXTURE)
    model = CrfEncoder(CONFIG)
    seeded_weights(model)
    model.eval()

    with torch.no_grad():
        got = model(torch.from_numpy(ref["signal"])).numpy()

    assert got.shape == ref["scores"].shape
    np.testing.assert_allclose(got, ref["scores"], rtol=1e-5, atol=2e-5)


def test_blank_is_entry_zero_of_each_state_group():
    """`score_index = state * (n_base+1) + label`, label 0 = stay.

    escapepod-demux's Rust decoder assumes this layout. If the blank moved to
    the end of each group the shapes would still line up and every call would
    be wrong, so pin it. Needs no trained weights: the splice is a property of
    the graph, not of what it learned.
    """
    cfg = EncoderConfig(chunk=200)
    model = CrfEncoder(cfg).eval()

    with torch.no_grad():
        out = model(torch.randn(2, 1, cfg.chunk))
    grouped = out.unflatten(-1, (cfg.n_states, cfg.n_base + 1))
    assert torch.all(grouped[..., 0] == cfg.blank_score)
    # and the move scores are bounded by tanh * scale
    assert grouped[..., 1:].abs().max() <= cfg.scale + 1e-6


def test_output_is_time_major():
    """`(T, N, n_score)`, not `(N, T, n_score)`.

    A consumer that assumes batch-major silently transposes every call rather
    than failing, and the boundary CNN in the same stack *is* batch-major — so
    the two contracts sit next to each other and cannot be told apart by shape
    when batch happens to equal T.
    """
    cfg = EncoderConfig(chunk=200)
    model = CrfEncoder(cfg).eval()
    with torch.no_grad():
        out = model(torch.randn(3, 1, cfg.chunk))
    assert out.shape == (cfg.t_len, 3, cfg.n_score)


def test_last_rnn_layer_runs_backwards():
    """Direction alternates so the last layer is always reversed.

    Get the parity wrong and the weights still load, the shapes still work, and
    the output is quietly wrong — the failure mode this module's docstring
    warns about, and the one nothing downstream can detect.
    """
    model = CrfEncoder(EncoderConfig(n_layers=5))
    assert [rnn.reverse for rnn in model.rnns] == [True, False, True, False, True]


def test_geometry_derives_from_config():
    cfg = EncoderConfig()
    assert cfg.n_states == 256
    assert cfg.n_score == 1280, "5 * 4^4, not 4^5 — blanks expand per state"
    assert cfg.t_len == cfg.chunk // cfg.stride


def test_rejects_unmapped_checkpoint_keys():
    """A silently-unloaded layer is worse than a failed load."""
    model = CrfEncoder()
    with pytest.raises(KeyError, match="does not know"):
        load_crf_state_dict(model, {"encoder.99.mystery.weight": torch.zeros(1)})


def test_loads_this_modules_own_naming_too():
    """Both namings must load through the one door.

    Models shipped before the trainer moved off the flat positional container
    carry `encoder.<i>.…` keys; everything trained since carries this module's
    `conv.*` / `rnns.*` / `linear.*`. Refusing either would strand real weights.
    """
    model = CrfEncoder()
    native = {k: torch.zeros_like(v) for k, v in model.state_dict().items()}
    load_crf_state_dict(CrfEncoder(), native)  # must not raise


def test_config_from_toml_derives_n_base_from_the_alphabet():
    """`n_base` is the alphabet minus the CTC blank; it is not a config key."""
    from leech.crf import encoder_config_from_toml

    cfg = encoder_config_from_toml(
        {
            "labels": {"labels": ["N", "A", "C", "G", "T"]},
            "global_norm": {"state_len": 4},
            "encoder": {"stride": 10, "winlen": 31, "scale": 5.0, "features": 96},
        }
    )
    assert (cfg.n_base, cfg.state_len, cfg.n_states, cfg.n_score) == (4, 4, 256, 1280)


def test_packaged_config_is_the_shipped_geometry():
    """The default config travels with the package, not with a corpus.

    Six scripts in escapepod-models once read it from scratch alone, so a purge
    would have left trained weights nobody could load.
    """
    from leech.crf import encoder_config_from_toml, load_config

    cfg = encoder_config_from_toml(load_config())
    assert (cfg.n_base, cfg.state_len, cfg.stride, cfg.features) == (4, 4, 10, 96)
    assert cfg.n_score == 1280


@pytest.mark.skipif(not torch.cuda.is_available(), reason="needs CUDA")
def test_compiled_tail_is_bit_identical_on_cuda(monkeypatch):
    """`LEECH_COMPILE=1` must not change a single score on CUDA.

    The fusion is worth 3.46 -> 0.92 ms, but only because it is EXACT. Two other
    candidate speedups on this path (fp16 autocast, fusing the decode's log into
    the kernel) were declined precisely because they were not, so this property
    is the whole justification and has to be pinned.
    """
    from leech.crf._analytic import _COMPILED, _compiled
    from leech.crf.encoder import _crf_tail

    torch.manual_seed(0)
    lin = torch.randn(20, 3, 256 * 4, device="cuda")
    eager = _crf_tail(lin, 256, 4, 5.0, 2.0)

    monkeypatch.setenv("LEECH_COMPILE", "1")
    _COMPILED.pop("crf_tail_test", None)
    compiled = _compiled("crf_tail_test", _crf_tail)(lin, 256, 4, 5.0, 2.0)

    assert torch.equal(eager, compiled), (eager - compiled).abs().max()


def test_cpu_forward_stays_eager_even_with_compile_requested(monkeypatch):
    """On CPU the fusion is NOT exact (4.77e-07), so it must not be used.

    CPU is where the reference comparison above runs and where the ONNX export
    traces. Enabling the fusion there would weaken the strongest claim this
    module makes to save nothing, since neither path is performance-critical on
    CPU.
    """
    torch.manual_seed(0)
    model = CrfEncoder(EncoderConfig(chunk=600)).eval()
    x = torch.randn(2, 1, 600)
    with torch.no_grad():
        plain = model(x)
        monkeypatch.setenv("LEECH_COMPILE", "1")
        requested = model(x)
    assert torch.equal(plain, requested)
